#!/usr/bin/env tsx
/**
 * Lexical-order SQL migration runner.
 *
 * Applies every `*.sql` file in `src/server/db/migrations/` in lexical order,
 * one file per transaction, tracking applied files in a `schema_migrations`
 * table. Connects as `app_migrator` — use `DATABASE_URL` for that role.
 *
 * drizzle-kit does not generate RLS/policy/grant/trigger DDL, so those land
 * as hand-written 0001/0002/0003 files alongside the 0000 init generated by
 * `pnpm db:generate`.
 */
import { readdir, readFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import postgres from "postgres";

const ROOT = path.resolve(fileURLToPath(new URL(".", import.meta.url)), "..");
const MIG_DIR = path.join(ROOT, "src", "server", "db", "migrations");

async function main() {
  const url = process.env.DATABASE_URL;
  if (!url) {
    console.error("DATABASE_URL is not set — required for migrations (connects as app_migrator)");
    process.exit(1);
  }

  const sql = postgres(url, { max: 1 });

  try {
    await sql`
      CREATE TABLE IF NOT EXISTS schema_migrations (
        name text PRIMARY KEY,
        applied_at timestamptz NOT NULL DEFAULT now()
      )
    `;

    const entries = await readdir(MIG_DIR, { withFileTypes: true });
    const files = entries
      .filter((e) => e.isFile() && e.name.endsWith(".sql"))
      .map((e) => e.name)
      .sort();

    if (files.length === 0) {
      console.log("No migration files found.");
      return;
    }

    const appliedRows = await sql<Array<{ name: string }>>`SELECT name FROM schema_migrations`;
    const applied = new Set(appliedRows.map((r) => r.name));

    let appliedCount = 0;
    for (const name of files) {
      if (applied.has(name)) {
        console.log(`  skip  ${name} (already applied)`);
        continue;
      }
      const body = await readFile(path.join(MIG_DIR, name), "utf8");
      console.log(`  apply ${name}`);
      await sql.begin(async (tx) => {
        await tx.unsafe(body);
        await tx`INSERT INTO schema_migrations (name) VALUES (${name})`;
      });
      appliedCount++;
    }

    console.log(`Applied ${appliedCount} migration(s).`);
  } finally {
    await sql.end({ timeout: 5 });
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
